version: '3.8'
services:
  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0.36
    env_file: ./env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=root_pwd"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - ticket-network

  # Aplicação Spring Boot
  app:
    image: dvfabricio/ticketsales:1.0  # Usar a imagem da sua aplicação
    build:
      context: .  # Diretório atual onde está o Dockerfile
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"  # Expondo a aplicação na porta 8080
    networks:
      - ticket-network

  # Servidor Nginx
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    networks:
      - ticket-network

# Volumes
volumes:
  mysql-data:

# Rede compartilhada entre os serviços
networks:
  ticket-network:
